### ISSUE TITLE
Linux support 

### ISSUE THREAD

**Issue by DASPRiD** [SDraw/openvr_widgets#1]
Hey there, this sounds like a really nice project! I was wondering if it could be ported over to Linux, possibly with the omission of window capture, as i know that this probably relies on windows only libraries.

**Comment by SDraw** [comment]
Yeah, that is possible. Here is testing build for it.
But I can't test it. SteamVR on Linux can't send videostream from dGPU via iGPU to HMD, and that is where my laptop limits me to use only null driver. I've managed to enable controllers for quick tests and it seems app works fine.
CPU load, memory usage, window capture interaction and keyboard widget presses aren't implemented yet.
[openvr_widgets_linux_x86-64-1.zip](https://github.com/SDraw/openvr_widgets/files/5071159/openvr_widgets_linux_x86-64-1.zip)

This idea will be on hold.

**Comment by DASPRiD** [comment]
Oh sweet, it's working! :) Tested with Index Knuckles!
It'd be even sweeter if it could show the charge of Vive Trackers as well :)

**Comment by SDraw** [comment]
I've configured auto-builds for Linux version, it's placed with Windows builds in latest release tab. I'll close this issue.
If you encounter problems with Linux version, create new issue. Soon I'll get my hands on window interaction and charge of trackers.
